id: quiz_on_crud
learningObjectives:
  - Assess knowledge about CRUD operations
hints:
  - Review CRUD operation methods for MongoDB.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: What's the typical method used in MongoDB for updating a document within a
              collection?
    - actionId: quiz_message
      name: quiz
      params:
        person: lucca
        options:
          - updateOne
          - find
          - insertOne
          - deleteOne
trigger:
  type: chat_form_submitted
  flowNode:
    switch:
      key: ${formSubmission}
      cases:
        A:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: Correct! `updateOne()` allows you to specify criteria and replace a
                      document accordingly.
            - actionId: finish_step
        B:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "`find` is for reading documents, not updating. Give it another shot."
            - actionId: replay_action
              params:
                actionName: quiz
        C:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "`insertOne` is for creating new documents. Try again."
            - actionId: replay_action
              params:
                actionName: quiz
        D:
          do:
            - actionId: bot_message
              params:
                person: lucca
                messages:
                  - text: "`deleteOne` is for removing documents, not updating them."
            - actionId: replay_action
              params:
                actionName: quiz
